[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bogde/HX711
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  adafruit/Adafruit GFX Library
  adafruit/Adafruit SSD1306
  jgromes/RadioLib